baseURL = 'https://memes.sapka.me'
languageCode = 'en-us'
title = "Michal's based meme collection"

[outputFormats.TXT]
mediaType = "text/plain"
sufix = "txt"
isPlainText = true

[outputs]
    home                   = [ "HTML", "RSS", "TXT" ]

